build:
  lifecycle:
    onInit: echo "Do thing on onInit event"
    onInstall: echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    plugins:
   # Local plugin
  - type: ./plugins/examplePlugin