[[plugins]]
  package = "./plugin/index.js"
  [plugins.inputs]
    # # optional config
    resultMode = "warn" # is "error" by default

    # # Developer only
    # debugMode = true # extra logging for plugin developers