build:
  lifecycle:
    onInit: echo "Do thing on onInit event"
    onInstall: echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    plugins:
      - type: ./plugins/examplePlugin